import type { Product, Ingredient } from '@shared/schema';

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Château Margaux',
    brand: 'Château Margaux',
    netVolume: '750ml',
    vintage: '2019',
    type: 'Red Wine',
    sugarContent: 'Dry',
    appellation: 'Margaux AOC',
    alcoholContent: '13.5%',
    country: 'France',
    sku: 'CM-2019-750',
    ean: '1234567890123',
    ingredients: 'Grapes, sulfur dioxide (E220), potassium sorbate (E202). Contains sulfites.',
    packagingGases: 'Nitrogen, Carbon dioxide',
    portionSize: '100ml',
    kcal: '83',
    kj: '347',
    fat: '0g',
    carbohydrates: '2.6g',
    organic: true,
    vegetarian: true,
    vegan: true,
    operatorType: 'Producer',
    operatorName: 'Château Example',
    operatorAddress: '123 Vineyard Road, Bordeaux, France',
    operatorInfo: 'Family-owned winery established in 1850',
    externalShortLink: 'https://short.ly/abc123',
    redirectLink: 'https://redirect.com/wine123',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
  {
    id: 2,
    name: 'Dom Pérignon',
    brand: 'Dom Pérignon',
    netVolume: '750ml',
    vintage: '2012',
    type: 'Champagne',
    sugarContent: 'Brut',
    appellation: 'Champagne AOC',
    alcoholContent: '12.5%',
    country: 'France',
    sku: 'DP-2012-750',
    ean: '1234567890124',
    ingredients: 'Grapes, sulfur dioxide (E220). Contains sulfites.',
    packagingGases: 'Carbon dioxide',
    portionSize: '100ml',
    kcal: '80',
    kj: '335',
    fat: '0g',
    carbohydrates: '2.5g',
    organic: false,
    vegetarian: true,
    vegan: false,
    operatorType: 'Producer',
    operatorName: 'Moët & Chandon',
    operatorAddress: '456 Champagne Ave, Épernay, France',
    operatorInfo: 'Prestigious champagne house since 1743',
    externalShortLink: 'https://short.ly/def456',
    redirectLink: 'https://redirect.com/champagne456',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
  {
    id: 3,
    name: 'Opus One',
    brand: 'Opus One',
    netVolume: '750ml',
    vintage: '2018',
    type: 'Red Wine',
    sugarContent: 'Dry',
    appellation: 'Napa Valley AVA',
    alcoholContent: '14.5%',
    country: 'United States',
    sku: 'OO-2018-750',
    ean: '1234567890125',
    ingredients: 'Grapes, sulfur dioxide (E220). Contains sulfites.',
    packagingGases: 'Nitrogen',
    portionSize: '100ml',
    kcal: '85',
    kj: '356',
    fat: '0g',
    carbohydrates: '2.8g',
    organic: false,
    vegetarian: true,
    vegan: true,
    operatorType: 'Producer',
    operatorName: 'Opus One Winery',
    operatorAddress: '789 Oakville Cross Rd, Oakville, CA',
    operatorInfo: 'Joint venture between Robert Mondavi and Baron Philippe de Rothschild',
    externalShortLink: 'https://short.ly/ghi789',
    redirectLink: 'https://redirect.com/opus789',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
];

export const mockIngredients: Ingredient[] = [
  {
    id: 1,
    name: 'Sulfur Dioxide',
    category: 'Preservative',
    eNumber: 'E220',
    allergens: ['sulfites'],
    details: 'Used as a preservative and antioxidant in wine production',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
  {
    id: 2,
    name: 'Potassium Sorbate',
    category: 'Preservative',
    eNumber: 'E202',
    allergens: [],
    details: 'Prevents yeast and mold growth in wine',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
  {
    id: 3,
    name: 'Ascorbic Acid',
    category: 'Antioxidant',
    eNumber: 'E300',
    allergens: [],
    details: 'Vitamin C used as an antioxidant to prevent oxidation',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
  {
    id: 4,
    name: 'Egg White',
    category: 'Fining Agent',
    eNumber: null,
    allergens: ['eggs'],
    details: 'Used for clarification and fining of red wines',
    createdAt: new Date('2023-05-31T01:01:41Z'),
    updatedAt: new Date('2023-05-31T01:02:10Z'),
  },
];

export const allergenOptions = [
  'gluten',
  'nuts',
  'milk',
  'eggs',
  'fish',
  'shellfish',
  'soy',
  'sulfites',
  'sesame',
  'mustard',
  'celery',
  'lupin',
];

export const categoryOptions = [
  'Preservative',
  'Antioxidant',
  'Fining Agent',
  'Acidifier',
  'Stabilizer',
  'Emulsifier',
  'Natural',
  'Other',
];

export const wineTypeOptions = [
  'Red Wine',
  'White Wine',
  'Rosé',
  'Champagne',
  'Sparkling',
];

export const operatorTypeOptions = [
  'Producer',
  'Distributor',
  'Retailer',
];
